-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {

  -- { -- Leap plugin for enhanced navigation
  --   'ggandor/leap.nvim',
  --   config = function()
  --     require('leap').add_default_mappings()
  --   end,
  -- },
  -- -- {
  -- --   'LintaoAmons/bookmarks.nvim',
  -- --   -- tag = "v0.5.4", -- optional, pin the plugin at specific version for stability
  -- --   dependencies = {
  -- --     { 'nvim-telescope/telescope.nvim' },
  -- --     { 'stevearc/dressing.nvim' }, -- optional: to have the same UI shown in the GIF
  -- --   },
  -- -- },
  -- {
  --   "theprimeagen/harpoon",
  --   branch = "harpoon2",
  --   dependencies = { "nvim-lua/plenary.nvim" },
  --   config = function()
  --     require("harpoon"):setup()
  --   end,
  --   keys = {
  --     { "<leader>H", function() require("harpoon"):list():add() end,     desc = "harpoon file", },
  --     {
  --       "<leader>h",
  --       function()
  --         local harpoon = require("harpoon")
  --         harpoon.ui:toggle_quick_menu(harpoon:list())
  --       end,
  --       desc = "harpoon quick menu",
  --     },
  --     { "<leader>1", function() require("harpoon"):list():select(1) end, desc = "harpoon to file 1", },
  --     { "<leader>2", function() require("harpoon"):list():select(2) end, desc = "harpoon to file 2", },
  --     { "<leader>3", function() require("harpoon"):list():select(3) end, desc = "harpoon to file 3", },
  --     { "<leader>4", function() require("harpoon"):list():select(4) end, desc = "harpoon to file 4", },
  --     { "<leader>5", function() require("harpoon"):list():select(5) end, desc = "harpoon to file 5", },
  --   },
  -- },
  -- {
  --   "gbprod/yanky.nvim",
  --   opts = {
  --     -- your configuration comes here
  --     -- or leave it empty to use the default settings
  --     sync_with_numbered_registers = false,
  --     system_clipboard = {
  --       sync_with_ring = false,
  --       clipboard_register = nil,
  --     },
  --   },
  -- },
  -- {
  --   "sindrets/diffview.nvim",
  --   enhanced_diff_hl = true, -- Enable enhanced diff highlighting
  --   use_icons = true,
  --   default = {
  --     layout = "diff2_horizontal", -- Start with a horizontal split
  --     winbar_info = false,         -- Disable winbar to reduce clutter
  --   },
  --   keymaps = {
  --     view = {
  --       -- Add a custom keymap to focus on one file
  --       { "n", "<leader>gf", "<cmd>DiffviewFocusFiles<cr>", { desc = "Focus on single file" } },
  --     },
  --   },
  -- },
  -- -- {
  -- --   "CopilotC-Nvim/CopilotChat.nvim",
  -- --   dependencies = {
  -- --     { "github/copilot.vim" },                       -- or zbirenbaum/copilot.lua
  -- --     { "nvim-lua/plenary.nvim", branch = "master" }, -- for curl, log and async functions
  -- --   },
  -- --   build = "make tiktoken",                          -- Only on MacOS or Linux
  -- --   opts = {
  -- --     -- See Configuration section for options
  -- --     model = 'claude-3.5-sonnet',
  -- --   },
  -- --   -- See Commands section for default commands if you want to lazy load on them
  -- -- },
  -- {
  --   'romgrk/barbar.nvim',
  --   dependencies = {
  --     'nvim-tree/nvim-web-devicons', -- OPTIONAL: for file icons
  --   },
  --   init = function() vim.g.barbar_auto_setup = false end,
  --   opts = {
  --     -- lazy.nvim will automatically call setup for you. put your options here, anything missing will use the default:
  --     -- animation = true,
  --     -- insert_at_start = true,
  --     -- …etc.
  --   },
  --   version = '^1.0.0', -- optional: only update when a new 1.x version is released
  -- },
}
