-- debug.lua
--
-- Shows how to use the DAP plugin to debug your code.
--
-- Primarily focused on configuring the debugger for Go, but can
-- be extended to other languages as well. That's why it's called
-- kickstart.nvim and not kitchen-sink.nvim ;)

return {}
-- return {
--   -- NOTE: Yes, you can install new plugins here!
--   'mfussenegger/nvim-dap',
--   -- NOTE: And you can specify dependencies as well
--   dependencies = {
--     -- Creates a beautiful debugger UI
--     'rcarriga/nvim-dap-ui',
--
--     -- Required dependency for nvim-dap-ui
--     'nvim-neotest/nvim-nio',
--
--     -- Installs the debug adapters for you
--     'williamboman/mason.nvim',
--     'jay-babu/mason-nvim-dap.nvim',
--
--     -- Add your own debuggers here
--     'leoluz/nvim-dap-go',
--   },
--   keys = function(_, keys)
--     local dap = require 'dap'
--     local dapui = require 'dapui'
--     return {
--       -- Basic debugging keymaps
--       { '<leader>6', dap.continue, desc = 'Debug: Continue' },
--       { '<leader>7', dap.step_over, desc = 'Debug: Step Over (Next Line)' },
--       { '<leader>8', dap.step_into, desc = 'Debug: Step Into' },
--       { '<leader>9', dap.step_out, desc = 'Debug: Step Out' },
--       { '<leader>0', dapui.toggle, desc = 'Debug: Toggle DAP UI' },
--       { '<leader>b', dap.toggle_breakpoint, desc = 'Debug: Toggle Breakpoint' },
--       {
--         '<leader>B',
--         function()
--           dap.set_breakpoint(vim.fn.input 'Breakpoint condition: ')
--         end,
--         desc = 'Debug: Set Breakpoint',
--       },
--       -- Attach to process by picking from list
--       {
--         '<leader>dp',
--         function()
--           local handle = io.popen('ps -eo pid,comm --no-headers 2>/dev/null')
--           if not handle then
--             vim.notify('Failed to get process list', vim.log.levels.ERROR)
--             return
--           end
--           local result = handle:read('*a')
--           handle:close()
--
--           local items = {}
--           for line in result:gmatch('[^\n]+') do
--             local pid, name = line:match('%s*(%d+)%s+(.+)')
--             if pid and name then
--               table.insert(items, {
--                 text = pid .. ' - ' .. name,
--                 pid = pid,
--                 name = name,
--               })
--             end
--           end
--
--           Snacks.picker({
--             title = 'Attach Debugger to Process',
--             items = items,
--             format = function(item)
--               return { { item.text } }
--             end,
--             confirm = function(picker, item)
--               picker:close()
--               if item then
--                 -- Get the executable path from /proc
--                 local exe_path = vim.fn.resolve('/proc/' .. item.pid .. '/exe')
--                 if exe_path == '' or exe_path:match('No such file') then
--                   exe_path = vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
--                 end
--                 dap.run({
--                   name = 'Attach to ' .. item.name,
--                   type = 'cppdbg',
--                   request = 'attach',
--                   processId = tonumber(item.pid),
--                   program = exe_path,
--                   cwd = vim.fn.getcwd(),
--                   MIMode = 'gdb',
--                   miDebuggerPath = '/usr/bin/gdb',
--                 })
--               end
--             end,
--           })
--         end,
--         desc = 'Debug: [P]ick process to attach',
--       },
--       -- Attach to process by entering PID
--       {
--         '<leader>da',
--         function()
--           vim.ui.input({ prompt = 'Enter PID: ' }, function(pid)
--             if pid and pid ~= '' then
--               -- Get the executable path from /proc
--               local exe_path = vim.fn.resolve('/proc/' .. pid .. '/exe')
--               if exe_path == '' or exe_path:match('No such file') then
--                 exe_path = vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
--               end
--               dap.run({
--                 name = 'Attach to PID ' .. pid,
--                 type = 'cppdbg',
--                 request = 'attach',
--                 processId = tonumber(pid),
--                 program = exe_path,
--                 cwd = vim.fn.getcwd(),
--                 MIMode = 'gdb',
--                 miDebuggerPath = '/usr/bin/gdb',
--               })
--             end
--           end)
--         end,
--         desc = 'Debug: [A]ttach to PID',
--       },
--       unpack(keys),
--     }
--   end,
--   config = function()
--     local dap = require 'dap'
--     local dapui = require 'dapui'
--
--     require('mason-nvim-dap').setup {
--       -- Makes a best effort to setup the various debuggers with
--       -- reasonable debug configurations
--       automatic_installation = true,
--
--       -- You can provide additional configuration to the handlers,
--       -- see mason-nvim-dap README for more information
--       handlers = {},
--
--       -- You'll need to check that you have the required things installed
--       -- online, please don't ask me how to install them :)
--       ensure_installed = {
--         -- Update this to ensure that you have the debuggers for the langs you want
--         'delve',
--         'cppdbg', -- For C/C++ debugging with GDB < 14
--       },
--     }
--
--     -- Dap UI setup
--     -- For more information, see |:help nvim-dap-ui|
--     dapui.setup {
--       -- Set icons to characters that are more likely to work in every terminal.
--       --    Feel free to remove or use ones that you like more! :)
--       --    Don't feel like these are good choices.
--       icons = { expanded = '▾', collapsed = '▸', current_frame = '*' },
--       controls = {
--         icons = {
--           pause = '⏸',
--           play = '▶',
--           step_into = '⏎',
--           step_over = '⏭',
--           step_out = '⏮',
--           step_back = 'b',
--           run_last = '▶▶',
--           terminate = '⏹',
--           disconnect = '⏏',
--         },
--       },
--     }
--
--     dap.adapters.gdb = {
--       type = 'executable',
--       command = 'gdb',
--       args = { '-i', 'dap' },
--     }
--
--     -- cppdbg adapter for GDB < 14 (uses vscode-cpptools)
--     dap.adapters.cppdbg = {
--       id = 'cppdbg',
--       type = 'executable',
--       command = vim.fn.stdpath('data') .. '/mason/bin/OpenDebugAD7',
--     }
--
--     dap.listeners.after.event_initialized['dapui_config'] = dapui.open
--     dap.listeners.before.event_terminated['dapui_config'] = dapui.close
--     dap.listeners.before.event_exited['dapui_config'] = dapui.close
--
--     -- Install golang specific config
--     require('dap-go').setup {
--       delve = {
--         -- On Windows delve must be run attached or it crashes.
--         -- See https://github.com/leoluz/nvim-dap-go/blob/main/README.md#configuring
--         detached = vim.fn.has 'win32' == 0,
--       },
--     }
--   end,
-- }
